course/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'course'

urlpatterns = [

    path('answer/<lession_id>', views.answer, name='answer'),
    path('yes_no/<yes_or_no>/<answer_id>', views.yes_no, name='yes_no'),

    path('enter/<course_id>', views.enter, name='enter'),
    path('cabinet', views.cabinet, name='cabinet'),
    
    path('lessions/<course_id>', views.lessions, name='lessions'),

    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

    path('', views.index, name='index'),

    path('<path>', views.table, name='table'),
    
    path('<path>/create', views.create, name='create'),
    path('<path>/delete/<id>', views.delete, name='delete'),
    path('<path>/update/<id>', views.update, name='update'),

    path('courses/<id>', views.course, name='course'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("course/", include("course.urls")),
    path("lab6/", include("lab6.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser

from lab6.models import User

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=41, null=False, unique=True)
    description = models.CharField(max_length=150)
    duration = models.CharField(max_length=20)
    mini_image = models.ImageField(upload_to= 'images/', null=True)
    image = models.ImageField(upload_to= 'images/', null=True)
    discipline = models.CharField(max_length=41, null=False)
    prof = models.CharField(max_length=41, null=False)
    color = models.CharField(max_length=41, null=False)


class User_Course(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)


class Schedule(models.Model):
    id = models.AutoField(primary_key=True)
    course = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    day = models.CharField(max_length=2, null=False)


class Lession(models.Model):
    id = models.AutoField(primary_key=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    num = models.IntegerField()
    title = models.CharField(max_length=41, null=False)
    file = models.FileField(upload_to= 'files/', null=True)


class User_Lession(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    lession = models.ForeignKey(Lession, on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to= 'files/', null=True)
    complete = models.IntegerField()

course/forms.py
from django import forms
from lab6.models import User


class SearchForm(forms.Form):
    search = forms.CharField(label="", empty_value="", required=False)


class User_LessionForm(forms.Form):
    file = forms.FileField(label="Файл", required=False)


class LessionForm(forms.Form):
    title = forms.CharField(label="Название", max_length=41)
    file = forms.FileField(label="Файл", required=False)


class LoginForm(forms.Form):
    email = forms.EmailField(label="email", max_length=20)
    password = forms.CharField(label="password", max_length=20, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    email = forms.EmailField(label="email", max_length=20)
    name = forms.CharField(label="name", max_length=20)
    surname = forms.CharField(label="surname", max_length=20)
    password = forms.CharField(label="password", max_length=20, widget=forms.PasswordInput)


class UserForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=20)
    name = forms.CharField(label="Имя", max_length=20)
    surname = forms.CharField(label="Фамилия", max_length=20)
    password = forms.CharField(label="Пароль", max_length=20, widget=forms.PasswordInput)
    group_owner = forms.IntegerField(label="Создатель курсов (0 или 1)")
    admin = forms.IntegerField(label="Администратор (0 или 1)")


class CourseForm(forms.Form):
    title = forms.CharField(label="Название курса", max_length=41)
    prof = forms.CharField(label="Профессия / Курс", max_length=40)
    discipline = forms.CharField(label="Дисциплина", max_length=40)
    description = forms.CharField(label="Описание", max_length=150)
    duration = forms.CharField(label="Длительность", max_length=20)
    mini_image = forms.ImageField(label="Миниатюра курса", required=False)
    image = forms.ImageField(label="Изображение курса", required=False)
    color = forms.CharField(label="Цвет курса", max_length=41)
    

course/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as lg, logout as lout

from lab6.models import User
from .models import *
from .forms import *

def yes_no(request, yes_or_no, answer_id):
    answer = User_Lession.objects.get(id=answer_id)
    answer.complete = yes_or_no
    answer.save()
    les = Lession.objects.get(id=answer.lession_id)
    course = Course.objects.get(id=les.course_id)
    return redirect('/course/lessions/' + str(course.id))

def answer(request, lession_id):
    ans = User_Lession.objects.filter(lession=lession_id)
    ans.delete()
    les = Lession.objects.get(id=lession_id)
    course_id = str(les.course_id)
    if request.method == "POST":
        try:
            form = User_LessionForm(request.POST, request.FILES)
            if form.is_valid():
                
                file = form['file'].value()

                answer = User_Lession(user=User.objects.get(id=request.user.id), lession=Lession.objects.get(id=lession_id), file=file, complete=-1)

                answer.save()

            return redirect('/course/lessions/' + course_id)
        except Exception as e:
            return HttpResponse(f"<h1>{e}</h1>")
    else:
        form = User_LessionForm()
        return render(request, "course/add.html", {'form': form, 'btn_name': 'Добавить ответ', 'path': 'lessions/' + str(course_id)})

def lessions(request, course_id):
    if request.method == "POST":
        try:
            form = LessionForm(request.POST, request.FILES)
            if form.is_valid():

                title = form['title'].value()
                file = form['file'].value()

                lessions = Lession.objects.filter(course=course_id)
                les_num = len(lessions)

                course = Course.objects.get(id=course_id)

                lession = Lession(course=course, num=les_num + 1, title=title, file=file)
                lession.save()

            return redirect('/course/lessions/' + course_id)
        except Exception as e:
            return HttpResponse(f"<h1>{e}</h1>")
    else:
        lessions = Lession.objects.filter(course=course_id)
        les_num = len(lessions)
        form = LessionForm()

        if not request.user.group_owner:
            user_lession = User_Lession.objects.filter(user=request.user.id)
        else:
            user_lession = []
            for i in lessions:
                for j in User_Lession.objects.filter(lession=i.id):
                    user_lession.append((j, User.objects.get(id=j.user_id)))

        return render(request, "course/lessions.html", {'form': form, 'lessions': lessions, 
        'les_num': les_num + 1, 'course_id': course_id, 'answers': user_lession})

def enter(request, course_id):

    user = User.objects.get(id=request.user.id)
    course = Course.objects.get(id=course_id)

    user_course = User_Course(user=user, course=course)
    user_course.save()

    return redirect('/course/cabinet')

def course(request, id):

    course = Course.objects.get(id=id)

    return render(request, "course/course.html", {'course': course})

def index(request):
    return render(request, "course/index.html")

def cabinet(request):
    products = []
    if request.user.admin:
        out = Course.objects.all()
        for product in out:
            products.append((
                product.id,
                product.title,
                product.prof,
                product.discipline,
                product.description,
                product.duration,
                product.mini_image.url,
                product.image.url,
                product.color
            ))
    elif request.user.group_owner:
        out = Course.objects.all()
        for product in out:
            if product.author_id == request.user.id:
                products.append((
                    product.id,
                    product.title,
                    product.prof,
                    product.discipline,
                    product.description,
                    product.duration,
                    product.mini_image.url,
                    product.image.url,
                    product.color,
                ))
    else:
        out = Course.objects.all()
        for product in out:
            if User_Course.objects.filter(course=product.id, user=request.user.id).exists():
                products.append((
                    product.id,
                    product.title,
                    product.prof,
                    product.discipline,
                    product.description,
                    product.duration,
                    product.mini_image.url,
                    product.image.url,
                    product.color
                ))

    return render(request, "course/cabinet.html", {'products': products, 'path': 'courses'})

def register(request):

    if request.method == "POST":
        try:
            form = RegisterForm(request.POST)
            if form.is_valid():

                email = form['email'].value()
                name = form['name'].value()
                surname = form['surname'].value()
                password = form['password'].value()

                group = User(email=email, name=name, surname=surname, password=password, username=email)
                group.save()
                return redirect('/course/')
        except Exception as e:
            return HttpResponse(f"<h1>{e}</h1>")
    else:
        form = RegisterForm()
        return render(request, "course/add.html", {'form': form, 'btn_name': 'Зарегистрироваться', 'path': 'reg'})

def login(request):
    if request.method == "POST":
        
        form = LoginForm(request.POST)
        if form.is_valid():

            email = form['email'].value()
            password = form['password'].value()

            user = authenticate(request, email=email, password=password)
            if user is not None:
                if user.is_active:
                    lg(request, user)
                    return redirect('/course/')
                else:
                    return HttpResponse('Disabled account')
        return redirect('/course/')
        
    else:
        form = LoginForm()
        return render(request, "course/add.html", {'form': form, 'btn_name': 'Войти', 'path': 'login'})

def logout(request):
    lout(request)
    return redirect('/course/')

def table(request, path):
        search = request.GET.get("search")
        filter_ = request.GET.get("filter")
        names = []
        products = []

        match path:

            case 'users':
                out = User.objects.all()
                for product in out:
                    products.append((
                        product.id,
                        product.email,
                        product.name,
                        product.surname,
                        product.password,
                        product.group_owner,
                        product.admin
                    ))
                names = ['Id', 'Email', 'Имя', 'Фамилия', 'Пароль', 'Создатель курсов', 'Админ', '']

            case 'courses':
                out = Course.objects.all()
                for product in out:
                    if product.author.id == request.user.id:
                        products.append((
                            product.id,
                            product.title,
                            product.description,
                        ))
                names = ['id', 'title', 'description' '']

            case 'view_courses':

                if request.method == "POST":
                    try:
                        form = SearchForm(request.POST)
                        if form.is_valid():
                            search = form['search'].value()
                            out = Course.objects.all()
                            p = 0
                            c = 0
                            for product in out:
                                if search in product.discipline:
                                    if User_Course.objects.filter(course=product.id, user=request.user.id).exists():
                                        continue
                                    if product.prof == 'Профессия':
                                        p += 1
                                    else:
                                        c += 1
                                    products.append((
                                        product.id,
                                        product.title,
                                        product.prof,
                                        product.discipline,
                                        product.description,
                                        product.duration,
                                        product.mini_image.url,
                                        product.image.url,
                                        product.color
                                    ))
                            
                        return render(request, "course/courses.html", {'products': products, 
                        'path': path, 'form': form, 'search': search, 'prof': p, 'curs': c})

                    except Exception as e:
                        return HttpResponse(f"<h1>{e}</h1>")
                else:

                    form = SearchForm()

                    p = 0
                    c = 0

                    out = Course.objects.all()

                    if not isinstance(search, str):
                        search = ''

                    if not isinstance(filter_, str):
                        filter_ = 'all'

                    for product in out:

course/templates/course/add.html
{% extends "course/index.html" %}
{% load static %}

{% block faq %}{% endblock faq %}

{% block content %}

<div class="main">
    
    <div class="block" style="justify-content: space-around;">
        <form class="add_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if path == 'reg' %}
                <p>Создайте свой профиль</p>
                <input placeholder="Имя" type="text" name="name" maxlength="20" required="" id="id_name">
                <input placeholder="Фамилия" type="text" name="surname" maxlength="20" required="" id="id_surname">
            {% elif path == 'login' %}
                <p style="margin-bottom: 1em;">Войдите в свой профиль</p>
            {% endif %}
            {% if path == 'reg' or path == 'login' %}
                <input style="margin-bottom: 1em;" placeholder="Электронная почта" type="email" name="email" maxlength="20" required="" id="id_email">
            {% endif %}
            {% if path == 'reg' %}
                <label for="id_password">Придумайте пароль</label>
            {% endif %}
            {% if path == 'reg' or path == 'login' %}
                <input placeholder="Пароль" type="password" name="password" maxlength="20" required="" id="id_password">
            {% elif path == 'cabinet' %}
                {{ form }}
            {% elif path == 'users' %}
                <label for="id_email">Email:</label>
                <input value="{{ arr.email }}" type="email" name="email" maxlength="20" required="" id="id_email">
                <label for="id_name">Имя:</label>
                <input value="{{ arr.name }}" type="text" name="name" maxlength="20" required="" id="id_name">
                <label for="id_surname">Фамилия:</label>
                <input value="{{ arr.surname }}" type="text" name="surname" maxlength="20" required="" id="id_surname">
                <label for="id_password">Пароль:</label>
                <input value="{{ arr.password }}" type="password" name="password" maxlength="20" required="" id="id_password">
                <label for="id_group_owner">Создатель курсов (0 или 1):</label>
                <input value="{{ arr.group_owner }}" type="number" name="group_owner" required="" id="id_group_owner">
                <label for="id_admin">Администратор (0 или 1):</label>
                <input value="{{ arr.admin }}" type="number" name="admin" required="" id="id_admin">
            {% else %}
                {{ form }}
            {% endif %}
            {% if path == 'login' %}
                <div class="zab">
                    <a style="margin-top: .4em;" href="/course/login">Забыли пароль</a>
                    <p style="margin-top: .4em;">?</p>
                </div>
            {% endif %}
            <button type="submit">{{ btn_name }}</button>
            <div class="redir">
                {% if path == 'reg' %}
                    <p>У вас уже есть профиль?</p>
                    <a href="/course/login">Зайдите</a>
                {% elif path == 'login' %}
                    <p style="margin-top: 1em;">Еще нет профиля?</p>
                    <a style="margin-top: 1em;" href="/course/register">Зарегистригуйтесь</a>
                {% endif %}
            </div>
        </form>
        {% if path == 'reg' or path == 'login'%}
            <img src="{% static 'course/images/Rectangle 121.svg' %}">
        {% endif %}
    </div>
    {% if path == 'reg'%}
    {% elif path == 'login' %}
    {% else %}
        <div class="block" style="justify-content: center;">
            <a class="back" href="/course/{{path}}">Назад</a>
        </div>
    {% endif %}
</div>

{% endblock content %}

course/templates/course/cabinet.html
{% extends "course/index.html" %}
{% load static %}

{% block faq %}{% endblock faq %}
{% block lc %}class="active"{% endblock lc %}

{% block content %}

<div class="main">
    {% if user.admin %}
    <div class="block">
        <p><a class="mng" href="users">Управление пользователями</a></p>
    </div>
    {% endif %}

    <div class="block">
        <p style="font-size: 32px; line-height: 39px;">
            {% if user.group_owner %}
                Мои курсы
            {% else %}
                Мое обучение
            {% endif %}
        </p>
    </div>
    <div class="block" style="margin-top: 2em; flex-wrap: wrap;">
        {% for line in products %}
            <div class="my_course" style="margin-bottom: 2em; background: {{line.8}}">
                <div class="my_course_text">
                    <p style="font-size: 16px;">{{line.2}}</p>
                    <p>{{line.1}}</p>
                    {% if user.group_owner %}
                    <div class="my_course_btns">
                        <a href="/course/courses/update/{{ line.0 }}">Удалить</a>
                        <a href="/course/courses/update/{{ line.0 }}">Редактировать</a>
                        <a href="/course/lessions/{{ line.0 }}">К занятиям</a>
                    </div>
                    {% else %}
                    <div class="my_course_btns">
                        <a href="/course/lessions/{{ line.0 }}">Продолжить</a>
                    </div>
                    {% endif %}
                </div>
                <img class="mini_image" src="{{ line.6 }}" alt="connect" style="max-height:300px">
            </div>

            <!-- <div class="main_stats" style="margin-bottom: 2em;">
                <div class="stats">
                    <div class="conv">
                        <p style="margin-bottom: 1.6em;">
                        {% if user.group_owner %}
                            конверсия курса</p>
                            <p>**%</p>
                        {% else %}
                            дней без перерыва</p>
                            <p>**</p>
                        {% endif %}
                    </div>
                    <div class="conv">
                        {% if user.group_owner %}
                            <p>количество учащихся</p>
                            <p>***</p>
                        {% else %}
                            <p style="margin-right: 0.8em;">дней максимум без перерыва</p>
                            <p>***</p>
                        {% endif %}
                        
                    </div>
                </div>
                <div class="stats">
                    <div class="conv">
                        <p>Активность за последние 7 дней</p>
                    </div>
                    <div class="conv">
                        <p style="margin-top: 1.6em;">задач решено: **</p>
                        <img style="margin-top: .4em;" src="{% static 'course/images/Rectangle 129.svg' %}">
                    </div>
                </div>
            </div> -->
            
        {% endfor %}
    </div>

    <div class="block" style="margin-top: 0.5em; flex-wrap: wrap;">
        {% if user.group_owner %}
        <a class="course" href="/course/courses/create" style="background: #F6F5F5;">
            <div class="course_text">
                    <p style="font-size: 32px; line-height: 39px; font-weight: 700; margin: .3em 0 0 .5em;">Новый курс</p>
        {% else %}
        <a class="course" href="/course/view_courses" style="background: #F6F5F5;">
            <div class="course_text">
                <p style="font-size: 24px; line-height: 29px; font-weight: 700; margin: 1.6em 0 0 1em;">К списку курсов</p>
        {% endif %}
            </div>
        </a>
    </div>

</div>

{% endblock content %}

course/templates/course/courses.html
{% extends "course/index.html" %}
{% load static %}

{% block faq %}{% endblock faq %}
{% block vc %}class="active"{% endblock vc %}

<script>
var search = location.search.substring(1);
alert(search[i]);
</script>

{% block content %}

<div class="main">
    <div class="block">
        <div class="srch">
            <img src="{% static 'course/images/Rectangle 96.svg' %}">
            <form method="post">
                {% csrf_token %}
                <input value="{{search}}" placeholder="Поиск" type="text" name="search" id="id_search">
            </form>
        </div>
    </div>
    {% if prof != 0 and filter != 'Курс'%}
        <div class="block">
            <p style="font-size: 36px; line-height: 44px;">Профессии</p>
        </div>
        <div class="block" style="margin-top: 1em; flex-wrap: wrap !important; padding: 0 0;">
            {% for line in products %}
                {% if line.2 == 'Профессия' %}
                    <a class="course" href="/course/courses/{{ line.0 }}" style="background: {{ line.8 }}">
                        <div class="course_text">
                            <p style="margin-bottom: 1.5em;">{{ line.2 }}</p>
                            <p style="font-size: 20px; line-height: 24px;">{{line.1}}</p>
                            <p style="margin-top: 4em;">{{line.5}}</p>
                        </div>
                        <img class="mini_image" src="{{ line.6 }}" alt="connect" style="max-height:300px">
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    {% if curs != 0 and filter != 'Профессия'%}
    <div class="block" {% if prof != 0 and filter != 'Курс'%} style="margin-top: 5em;" {% endif %}>
        <p style="margin: 0 0 .5em 0; font-size: 36px; line-height: 44px;">Курсы</p>
    </div>
    <div class="block" style="flex-wrap: wrap !important;">
        {% for line in products %}
            {% if line.2 == 'Курс' %}
                <a class="course" href="/course/courses/{{ line.0 }}" style="background: {{ line.8 }} ">
                    <div class="course_text">
                        <p style="margin-bottom: 1.5em;">{{ line.2 }}</p>
                        <p style="font-size: 20px; line-height: 24px;">{{line.1}}</p>
                        <p style="margin-top: 4em;">{{line.5}}</p>
                    </div>
                    <img class="mini_image" src="{{ line.6 }}" alt="connect" style="max-height:300px">
                </a>
            {% endif %}
        {% endfor %}
        
    </div>
    {% endif %}
    
</div>
    
{% endblock content %}

course/templates/course/lessions.html
{% extends "course/index.html" %}
{% load static %}

{% block faq %}{% endblock faq %}

{% block content %}

<div class="main">
    <div class="block">
        <p class="zan">Занятия</p>
    </div>

    <div class="block">
        <div class="lessions">
        {% for line in lessions %}
                <form>
                    <div class="text_lessions">
                        <p>Занятие {{ line.num }}</p>
                        <p>{{line.title}}</p>
                    </div>
                    {% if user.group_owner %}
                    <div class="btn_les">
                        <a id="upd" href="/course/lessions/update/{{ line.id }}">Изменить</a>
                        <a id="del" href="/course/lessions/delete/{{ line.id }}">Удалить</a>
                    </div>
                    {% else %}
                    <div class="btn_les">
                        <a href="{{ line.file.url }}">Скачать файл задания</a>
                        <a href="/course/answer/{{ line.id }}">Прикрепить ответ</a>
                    </div>
                    {% endif %}
                </form>

                {% if user.group_owner %}
                    {% for ans, name in answers %}
                        {% if ans.lession_id == line.id %}
                            <form style="margin-bottom: 4em;">
                                <div class="text_lessions">
                                    <p>Ответ от: {{ name.name }} {{ name.surname }}</p>
                                </div>
                                <a href="{{ ans.file.url }}">{{ ans.file }}</a>
                                <div class="btn_les">
                                    {% if ans.complete == -1 %}
                                        <a href="/course/yes_no/1/{{ ans.id }}">Верно</a>
                                        <a href="/course/yes_no/0/{{ ans.id }}">Неверно</a>
                                    {% else %}
                                        <a href="/course/yes_no/-1/{{ ans.id }}">Изменить оценку</a>
                                    {% endif %}
                                </div>
                            </form>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <form style="margin-bottom: 4em;">
                        <div class="text_lessions">
                            <p>Ваш ответ</p>
                        </div>
                        {% for ans in answers %}
                            {% if ans.lession_id == line.id %}
                                <a href="{{ ans.file.url }}">{{ ans.file }}</a>
                                {% if ans.complete == -1 %}
                                    <p>Ожидает проверки</p>
                                    <div class="btn_les">
                                        <a href="/course/answer/{{ line.id }}">Изменить ответ</a>
                                        <a id="del" href="/course/answer/delete/{{ line.id }}">Удалить</a>
                                    </div>
                                {% elif ans.complete == 0 %}
                                    <p style="color: darkred;">Неверно</p>
                                    <div class="btn_les">
                                        <a href="/course/answer/{{ line.id }}">Изменить ответ</a>
                                        <a id="del" href="/course/answer/delete/{{ line.id }}">Удалить</a>
                                    </div>
                                {% else %}
                                    <p style="color: green;">Верно</p>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        
                    </form>
                {% endif %}
        {% endfor %}
        </div>
    </div>

    {% if user.group_owner %}
        <div class="block">
            <div class="add_lession" id="new">
                <form method = "post", enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Занятие {{ les_num }}</p>
                    <input placeholder="Название занятия" type="text" name="title" maxlength="41" required="" id="id_title">
                    <input type="file" name="file" id="id_file">
                    <button type="submit">Подтвердить</button>
                </form>
            </div>
        </div>
        <div class="block" id="add">
            <button class="add_rem" onclick="add_new();">Добавить занятие</button>
        </div>
        <div class="block" id="rem">
            <button class="add_rem" onclick="add_rem();">Отмена</button>
        </div>
    {% endif %}
</div>

{% endblock content %}

{% block footer %}
{% endblock footer %}

course/templates/course/table.html
{% extends "course/index.html" %}

{% block faq %}{% endblock faq %}

{% block content %}
<div class="main">
    <div class="block">
        <p><a class="table_btn" href="/course/cabinet">Вернуться назад</a></p>
        <p><a class="table_btn" href="/course/{{ path }}/create">Создать</a></p>
    </div>
    <div class="block">
        <table>
            <tr style="background: #D9D9D9;">
                {% for name in names %}
                <td>{{ name }}</td>
                {% endfor %}
            </tr>
            {% for line in products %}
            <tr>
                {% for elem in line %}
                    <td>{{ elem }}</td>
                {% endfor %}
                
                <td>
                    <p><a class="tbl_btn" href="/course/{{ path }}/update/{{ line.0 }}">Обновить</a></p>
                    <p><a class="tbl_btn" href="/course/{{ path }}/delete/{{ line.0 }}">Удалить</a></p>
                </td>
        
            </tr>
        
        {% endfor %}
        </table>
    </div>
    
</div>

        
    
{% endblock content %}